$engine: 3
$onesync: on
name: Keystone Framework
author: Case
description: Keystone Framework Beta Build.

tasks:

  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  # Download and setup OxMySQL
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    dest: ./resources/[standalone]/oxmysql.zip
  - action: unzip
    src: ./resources/[standalone]/oxmysql.zip
    dest: ./resources/[standalone]

  # Download Bob74_ipl
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  # Download PMA-Voice
  - action: download_file
    url: https://github.com/AvarianKnight/pma-voice
    dest: ./resources/[standalone]/pma-voice.zip
  - action: unzip
    src: ./resources/[standalone]/pma-voice.zip
    dest: ./resources/[standalone]/pma-voice

  # Download fivem_utils
  - action: download_file
    url: https://github.com/keystonehub/fivem_utils
    dest: ./resources/[standalone]/fivem_utils.zip
  - action: unzip
    src: ./resources/[standalone]/fivem_utils.zip
    dest: ./resources/[standalone]/fivem_utils

  # Download Keystone
  - action: download_file
    url: https://github.com/keystonehub/keystone
    dest: ./resources/[core]/keystone.zip
  - action: unzip
    src: ./resources/[core]/keystone.zip
    dest: ./resources/[core]

  # Run SQL setup
  - action: execute_sql
    file: ./resources/[core]/setup.sql

  # Move server.cfg to root
  - action: move_path
    src: ./resources/[core]/server.cfg
    dest: ./server.cfg

  # Move logo to root
  - action: move_path
    src: ./resources/[core]/server_logo.png
    dest: ./server_logo.png

  # Remove unwanted files
  - action: remove_path
    path: ./resources/[core]/readme.md
  - action: remove_path
    path: ./resources/[core]/recipe.yaml
  - action: remove_path
    path: ./resources/[core]/setup.sql

  # Clean up temporary files
  - action: remove_path
    path: ./tmp
