$engine: 3
$onesync: on
name: Keystone Framework
author: Case
description: Keystone Framework Beta Build.

tasks:

  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  # Download Keystone
  - action: download_github
    src: https://github.com/keystonehub/keystone/
    ref: main
    dest: ./resources/[core]

  # Download and unzip oxmysql
  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[standalone]
    src: ./tmp/files/oxmysql.zip

  # Download bob74_ipl
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[standalone]/bob74_ipl

  # Download pma-voice
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: master
    dest: ./resources/[standalone]/pma-voice

  # Download fivem_utils
  - action: download_file
    src: hhttps://github.com/keystonehub/fivem_utils
    ref: master
    dest: ./resources/[standalone]/fivem_utils

  # Waste time
  - action: waste_time
    seconds: 3 

  # Connect DB
  - action: connect_database 

  # Run SQL setup
  - action: execute_sql
    file: ./resources/[core]/setup.sql

  # Move server.cfg to root
  - action: move_path
    src: ./resources/[core]/server.cfg
    dest: ./server.cfg

  # Move logo to root
  - action: move_path
    src: ./resources/[core]/server_logo.png
    dest: ./server_logo.png

  # Remove unwanted files
  - action: remove_path
    path: ./resources/[core]/readme.md
  - action: remove_path
    path: ./resources/[core]/recipe.yaml
  - action: remove_path
    path: ./resources/[core]/setup.sql

  # Clean up temporary files
  - action: remove_path
    path: ./tmp
